### ISSUE TITLE
[Bug] Can't drag

### ISSUE THREAD

**Issue by 4ykhxn** [FlamedDogo99/EaglerMobile#30] opened 2024-06-20 15:01 UTC
When i drag to craft it drops the item. It's impossible to play survival. Pls fix it

**Comment by FlamedDogo99** [comment] 2024-06-20 16:29
Hi @4ykhxn, this issue is a duplicate of #21 and #26. If you have any additional information you wish to provide about this topic, please post it in #21.

Thanks.

**Closed by FlamedDogo99** 2024-06-20 16:29 UTC
Labels: bug
