### ISSUE TITLE
Can't drag

### ISSUE THREAD

**Issue by 4ykhxn** [FlamedDogo99/EaglerMobile#26] opened 2024-06-18 16:17 UTC
When i drag it drops the items and it's not possible to craft on survival mode. Pls fix it

**Comment by FlamedDogo99** [comment] 2024-06-18 21:45
Hi @4ykhxn, this issue is a duplicate of #21. If you have any additional information you wish to provide about this topic, please post it in #21.

Thanks.

**Closed by FlamedDogo99** 2024-06-18 21:45 UTC
Labels: bug, duplicate
